### ISSUE TITLE
wlan0 -> wlp2s0

### ISSUE THREAD

**Issue by stkle** [nicolastrote/conkyForGnome3#1]
Had to add my wlan interface, which is `wlp2s0` and not `wlan0`. Maybe add this as an alternative in the folder?

Didn't touch the uncommented lines.

```
# NETWORK
# ${font Arial:bold:size=8}${color grey74}NETWORK ${color grey74}${hr 2}
# $font${color white}IP on wlan0 $alignr ${addr wlan0}
# Down $alignr ${downspeed wlan0} kb/s
# Up $alignr ${upspeed wlan0} kb/s
# Downloaded: $alignr  ${totaldown wlan0}
# Uploaded: $alignr  ${totalup wlan0}
# ${color white}${downspeedgraph wlan0 32,150 ff0000 0000ff} ${color white}${upspeedgraph wlan0 32,150 0000ff ff0000}

${font Arial:bold:size=8}${color grey74}NETWORK wlp2s0${color grey74}${hr 2}
$font${color white}IP on wlp2s0 $alignr ${addr wlp2s0}
Down $alignr ${downspeed wlp2s0} kb/s
Up $alignr ${upspeed wlp2s0} kb/s
Downloaded: $alignr  ${totaldown wlp2s0}
Uploaded: $alignr  ${totalup wlp2s0}
${color white}${downspeedgraph wlp2s0 32,150 ff0000 0000ff} ${color white}${upspeedgraph wlp2s0 32,150 0000ff ff0000}
```

**Comment by nicolastrote** [comment]
Thanks stkle,

But there is so much name of interfaces ( wlan0, eth0 for the most common
name) but you can find others like yours.
I write some lines on it in the readme file ;)
That s somewhat better
have a good day

**Comment by stkle** [comment]
Agreed, just got carried away last night :)

Working on some changes regarding §{pre_exec lsb_release, since pre_exec got removed in conky 1.10. I presume you use conky 1.9? Eighter fix it, or comment it in the readme.

Here's what i patch to get it working so far:
`${font Arial:bold:size=10}${color white}${execpi 9999 lsb_release -ds | cut -f 2| tr "[:upper:]" "[:lower:]"}$alignr${execpi 9999 lsb_release -cs | cut -f 2| tr "[:upper:]" "[:lower:]"}
`
Unsure about it being an unnecessary resource-hog or not.
Looking into lua to generate lsb_release at startup.

**Comment by nicolastrote** [comment]
I got the 1.9, but your code is ok on 1.10, so I comit it with some features.
Thanks stkle
